services:
  server:
    image: currency-exchange-server
    container_name: 'currency-exchange-server'
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - redis
      - mongo-db
    environment:
      - TZ=Europe/Kyiv
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
        - action: rebuild
          path: ./server/package.json
          target: /app/package.json

  mongo-db:
    image: mongo:latest
    container_name: 'mongo-db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qweasdzxc0987
      MONGO_INITDB_DATABASE: currency-exchange
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/_volume/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongodb:/data/db

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - "6379:6379"

  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis